// Generated by https://quicktype.io

export interface Account {
  address: string
  balance: number
  code: string
  contracts: Record<string, string>
  keys: Key[]
}

export interface Key {
  index: number
  publicKey: string
  signAlgo: number
  signAlgoString: string
  hashAlgo: number
  hashAlgoString: string
  weight: number
  sequenceNumber: number
  revoked: boolean
}
