// Generated by https://quicktype.io

export interface FlowUser {
  f_type: string
  f_vsn: string
  addr: string | null
  cid: string | null
  loggedIn: boolean | null
  services: FlowWalletService[]
}

export interface FlowWalletService {
  f_type: string
  f_vsn: string
  type: string
  uid: string
  id?: string
  identity?: Identity
  scoped?: Scoped
  provider?: FlowWalletProvider
  authn?: string
  method?: string
  address?: string
  addr?: string
  keyId?: number
  endpoint?: string
  params?: FlowWalletParams
  data?: FlowUserData
}

export interface FlowUserData {
  f_type: string
  f_vsn: string
  email: Email
}

export interface Email {
  email: string
  email_verified: boolean
}

export interface Identity {
  address: string
  keyId?: number
  addr?: string
  f_type?: string
  f_vsn?: string
}

export interface FlowWalletParams {
  sessionId: string
}

export interface FlowWalletProvider {
  address: string
  name: string
  icon: string
  description?: string
}

export interface Scoped {
  email: string
}
